### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [BitFdev/BitF#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repositor

File in question: 
      BitF-source-code/LICENSE

**Comment by BitFdev** [comment]
Thank you for letting us know about this oversight - We have updated the LICENSE file to reflect the copyrights.
Thanks.

**Comment by Iconoclasta** [comment]
Thank you, we will go through your repository and double check everything has been fixed.

**Comment by BitFdev** [comment]
Let us know if you see anything else and we will correct it.

Thanks.

**Comment by Iconoclasta** [comment]
Everything seems in order. Thanks for the collaboration. I will close this issue now.

**Comment by Iconoclasta** [comment]
ps I would recommend deleting one of the two license files. This is purely for aesthetic reasons.
